### ISSUE TITLE
update link to developer blog

### ISSUE THREAD

**Issue by hturner** [r-devel/r-devel.github.io#2]
Now https://blog.r-project.org/

**Comment by hturner** [comment]
Also on sub-pages e.g. slack.md

**Comment by netique** [comment]
Yes, I can confirm the button with shared Slack invitation is not working anymore.

**Comment by hturner** [comment]
The shared Slack invitation is a different link - I thought that had already been updated, I've just changed it now.

**Comment by hturner** [comment]
Fixed in d662aca4fc23fa7c3b837483c64624732e23b250
